name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "2.7"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} (Miniconda)
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Conda info
      shell: bash -l {0}
      run: conda info

    - name: "Init conda"
      shell: bash -l {0}
      run: |
          conda init bash

    - name: Conda install dependencies
      shell: bash -l {0}
      run: |
           conda create -n root-nightly -y -c https://root.cern/download/conda-nightly/latest -c conda-forge root-nightly cmake pytest pytest-benchmark pytest-csv numpy numba

    - name: Configure and build
      shell: bash -l {0}
      run: |
           conda activate root-nightly
           mkdir -p build && cd build
           cmake ..
           cmake --build .

    - name: Run benchmarks
      shell: bash -l {0}
      run: |
           conda activate root-nightly
           export PYTHONHOME=$CONDA
           cd build
           ctest -V
