name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} (Miniconda)
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: "Configure conda"
      shell: bash
      run: |
          conda init --all

    - name: Conda install dependencies
      shell: bash
      run: |
           conda create -n root-nightly -y -c https://root.cern/download/conda-nightly/latest -c conda-forge root-nightly cmake pytest pytest-benchmark pytest-csv numpy numba
           conda activate root-nightly

    - name: Configure and build
      shell: bash
      run: |
           mkdir -p build && cd build
           $CONDA/bin/cmake ..
           cmake --build .

    - name: Run benchmarks
      shell: bash
      run: |
           export PYTHONHOME=$CONDA
           cd build
           $CONDA/bin/ctest -V
